### ISSUE TITLE
support generating rust and/or typescript?

### ISSUE THREAD

**Issue by qzmfranklin** [nodejs/llparse#33]
I saw a `refactor/type-script` branch which was `[This branch is] 281 commits ahead, 223 commits behind master.`

I want to compile the stuff in rust or typescript for browser-based applications.

How's the interest and bandwidth?

**Comment by indutny** [comment]
That branch had slightly different meaning and should probably removed by now. Sorry for confusion!

Rust backend would be a great addition, but I'm afraid that JavaScript (and incidentally) TypeScript output is significantly slower than C/bitcode due to absence of `goto` statement in JS. There is an undocumented `generateJS: true` option for compiler that you could give a try to and see if it works for you: https://github.com/nodejs/llparse/blob/master/src/compiler/index.ts#L42
